SELECT avg(e.salary)
FROM EMPLOYEES e;


SELECT e.FIRST_NAME, e.DEPARTMENT_ID,
	CASE 
		--WHEN e.DEPARTMENT_ID >=10 AND e.DEPARTMENT_ID <=50 THEN  e.DEPARTMENT_NAME = 'A-TEAM'--
		--WHEN e.DEPARTMENT_ID >=60 AND e.DEPARTMENT_ID <=100 THEN e.DEPARTMENT_NAME = 'B-TEAM'--
		--WHEN e.DEPARTMENT_ID >=110 AND e.DEPARTMENT_ID <=150 THEN e.DEPARTMENT_NAME = 'C-TEAM'--
		WHEN e.DEPARTMENT_ID IN (10, 20, 30, 40, 50) THEN 'A-TEAM'
		WHEN e.DEPARTMENT_ID IN (60, 70, 80, 90, 100) THEN 'B-TEAM'
		WHEN e.DEPARTMENT_ID IN (110, 120, 130, 140, 150) THEN 'A-TEAM'
		ELSE '팀 없음'
	END TEAM
FROM EMPLOYEES e;





SELECT j.MAX_SALARY "최고 임금", 
	   j.MIN_SALARY "최저 임금", 
	   j.MAX_SALARY - j.MIN_SALARY  "최고 임금 - 최저 임금"
FROM JOBS j;


SELECT TO_CHAR(max(e.HIRE_DATE), 'YYYY"년 "MM"월 "DD"일"') 
FROM EMPLOYEES e;



SELECT e.JOB_ID, AVG(e.SALARY), MAX(e.SALARY), MIN(e.SALARY)  
FROM EMPLOYEES e 
ORDER BY e.JOB_ID DESC;




SELECT MIN(e.HIRE_DATE)
FROM EMPLOYEES e; 




SELECT e.DEPARTMENT_ID, round(AVG(e.SALARY)) avg, round(MIN(e.SALARY)) min, round(AVG(e.SALARY)-MIN(e.SALARY)) dif
FROM EMPLOYEES e 
GROUP BY e.DEPARTMENT_ID
HAVING AVG(e.SALARY)-MIN(e.SALARY)<2000
ORDER BY AVG(e.SALARY)-MIN(e.SALARY) desc;



SELECT e.JOB_ID, MAX(SALARY)-MIN(e.SALARY) 
FROM EMPLOYEES e 
GROUP BY e.JOB_ID 
ORDER BY 2 DESC;





