SELECT e.EMPLOYEE_ID, e.FIRST_NAME , d.DEPARTMENT_NAME, e2.FIRST_NAME 
FROM EMPLOYEES e , DEPARTMENTS d , EMPLOYEES e2 
WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID AND e2.EMPLOYEE_ID  = e.MANAGER_ID;



SELECT r.REGION_NAME , c.COUNTRY_NAME 
FROM REGIONS r , COUNTRIES c 
WHERE r.REGION_ID = c.REGION_ID 
ORDER BY r.REGION_NAME DESC, c.COUNTRY_NAME DESC;


SELECT *
FROM EMPLOYEES e


SELECT d.DEPARTMENT_ID, d.DEPARTMENT_NAME , e.FIRST_NAME, l.CITY, c.COUNTRY_NAME, r.REGION_NAME
FROM DEPARTMENTS d, EMPLOYEES e, COUNTRIES c , LOCATIONS l , REGIONS r 
WHERE d.MANAGER_ID  = e.EMPLOYEE_ID  
	AND l.COUNTRY_ID = c.COUNTRY_ID 
	AND c.REGION_ID = r.REGION_ID 
	AND d.LOCATION_ID = l.LOCATION_ID; 






--

SELECT e.EMPLOYEE_ID , e.FIRST_NAME 
FROM JOB_HISTORY jh, EMPLOYEES e, JOBS j 
WHERE jh.EMPLOYEE_ID = e.EMPLOYEE_ID AND j.JOB_TITLE = 'Public Accountant';



SELECT e.EMPLOYEE_ID , e.FIRST_NAME, e.LAST_NAME , d.DEPARTMENT_NAME 
FROM EMPLOYEES e, DEPARTMENTS d 
WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID 
ORDER BY e.LAST_NAME ;
