SELECT e.FIRST_NAME, e.DEPARTMENT_ID , d.DEPARTMENT_NAME , d.DEPARTMENT_ID  
FROM EMPLOYEES e, DEPARTMENTS d 
WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID  



SELECT e.FIRST_NAME , j.JOB_TITLE 
FROM EMPLOYEES e , JOBS j; 



SELECT e.FIRST_NAME, d.DEPARTMENT_NAME, j.JOB_TITLE 
FROM EMPLOYEES e , DEPARTMENTS d, JOBS j 
WHERE e.DEPARTMENT_ID  = d.DEPARTMENT_ID AND e.JOB_ID = j.JOB_ID ;



SELECT e.FIRST_NAME, e2.FIRST_NAME  
FROM EMPLOYEES e, EMPLOYEES e2 
WHERE e.MANAGER_ID = e2.EMPLOYEE_ID;



SELECT e.DEPARTMENT_ID , e.FIRST_NAME , d.DEPARTMENT_NAME 
FROM EMPLOYEES e RIGHT OUTER JOIN DEPARTMENTS d 
ON e.DEPARTMENT_ID = d.DEPARTMENT_ID;


SELECT e.DEPARTMENT_ID , e.FIRST_NAME , d.DEPARTMENT_NAME 
FROM EMPLOYEES e , DEPARTMENTS d 
WHERE e.DEPARTMENT_ID (+) = d.DEPARTMENT_ID; 



SELECT e.DEPARTMENT_ID, e.FIRST_NAME, d.DEPARTMENT_NAME 
FROM EMPLOYEES e FULL OUTER JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID 





