SELECT first_name || ' ' || last_name "이름", 
	   salary "월급", 
	   phone_number "전화번호",
	   hire_date "입사일"
FROM EMPLOYEES
ORDER BY hire_date;


SELECT e.JOB_ID, e.SALARY  
FROM EMPLOYEES e 
ORDER BY e.SALARY DESC;


SELECT first_name || ' ' || last_name, e.MANAGER_ID, e.COMMISSION_PCT, e.SALARY 
FROM EMPLOYEES e 
WHERE e.MANAGER_ID IS NOT NULL 
	  AND e.COMMISSION_PCT IS NULL 
	  AND e.SALARY >3000;


SELECT j.JOB_TITLE, j.MAX_SALARY 
FROM JOBS j
WHERE j.MAX_SALARY >= 10000 
ORDER by j.MAX_SALARY DESC;


SELECT e.FIRST_NAME, e.SALARY, NVL(e.COMMISSION_PCT, 0)
FROM EMPLOYEES e 
WHERE e.SALARY < 14000 AND e.SALARY >= 10000 
ORDER BY e.SALARY DESC;


SELECT e.first_name, e.salary, TO_CHAR(e.HIRE_DATE, 'YYYY-MM'), e.DEPARTMENT_ID 
FROM EMPLOYEES e
WHERE e.DEPARTMENT_ID in(10, 90, 100);


SELECT e.FIRST_NAME, e.SALARY 
FROM EMPLOYEES e
WHERE e.FIRST_NAME LIKE '%S%' OR e.FIRST_NAME LIKE '%s%';


SELECT e.FIRST_NAME, e.SALARY 
FROM EMPLOYEES e
WHERE UPPER(e.FIRST_NAME) LIKE '%S%';


SELECT d.DEPARTMENT_NAME 
FROM DEPARTMENTS d 
ORDER BY LENGTH(d.DEPARTMENT_NAME) DESC;


SELECT *
FROM EMPLOYEES e ;


SELECT e.FIRST_NAME, e.SALARY, REPLACE (e.PHONE_NUMBER, '.', '-'), TO_CHAR(e.HIRE_DATE, 'YYYY-MM')
FROM EMPLOYEES e 
WHERE HIRE_DATE < '2003-12-31';
