
SELECT e.EMPLOYEE_ID, e.FIRST_NAME ||' '||  e.LAST_NAME 
FROM JOB_HISTORY jh , JOBS j, EMPLOYEES e 
WHERE jh.JOB_ID = j.JOB_ID 
AND e.EMPLOYEE_ID = jh.EMPLOYEE_ID 
AND j.JOB_TITLE = 'Public Accountant';


SELECT e.EMPLOYEE_ID, e.FIRST_NAME, e.LAST_NAME , d.DEPARTMENT_NAME 
FROM EMPLOYEES e, DEPARTMENTS d 
WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID 
ORDER BY LAST_NAME;


SELECT e.EMPLOYEE_ID, e.FIRST_NAME, e.LAST_NAME , d.DEPARTMENT_NAME 
FROM EMPLOYEES e, DEPARTMENTS d 
WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID(+) 
-- 널이 없는 곳에 넣어준다는 느낌..
ORDER BY LAST_NAME;


SELECT e.EMPLOYEE_ID , e.LAST_NAME, e.HIRE_DATE
FROM EMPLOYEES e , EMPLOYEES e2 
WHERE e.MANAGER_ID  = e2.EMPLOYEE_ID AND e.HIRE_DATE < e2.HIRE_DATE 



