DROP TABLE POST_SEJONG;
CREATE TABLE "POST_SEJONG"
   (    "ZIPCODE" VARCHAR2(5),
    "SIDO" VARCHAR2(30),
    "SIDOE" VARCHAR2(60),
    "SIGUNGU" VARCHAR2(30),
    "SIGUNGUE" VARCHAR2(60),
    "EUPMYUN" VARCHAR2(30),
    "EUPMYUNE" VARCHAR2(60),
    "DOROCODE" VARCHAR2(12),
    "DORO" VARCHAR2(80),
    "DOROE" VARCHAR2(80),
    "UNDERGROUND" CHAR(1),
    "BUILDINGNO1" NUMBER,
    "BUILDINGNO2" NUMBER,
    "BUILDINGMANAGENO" VARCHAR2(25),
    "DARYANG" VARCHAR2(40),
    "BUILDING" VARCHAR2(200),
    "DONGCODE" VARCHAR2(10),
    "DONG" VARCHAR2(20),
    "RI" VARCHAR2(20),
    "DONGADMIN" VARCHAR2(40),
    "SAN" VARCHAR2(1),
    "ZIBUN1" NUMBER,
    "ZIBUNSERIAL" VARCHAR2(2),
    "ZIBUN2" NUMBER,
    "OLDZIPCODE" VARCHAR2(6),
    "ZIPCODESERIAL" VARCHAR2(3)
   ) ;
   
   COMMIT;
   
   select count(*) from POST_SEJONG ps;
   
   select *
   from POST_SEJONG ps;
   
   select *
   from POST_SEJONG ps
   where ps.BUILDING || ps.DONG LIKE '%한솔%';
